export default function database() {
    return [{
        text: '数据库',
        base: '/database',
        link: '/index',
        collapsed: true,
        items: [{
            text: '第一页',
            base: 'database/page1',
            link: '/index',
            collapsed: true,
            items: [
                {text: '175. 组合两个表', link: '/175'},
                {text: '176. 第二高的薪水', link: '/176'},
                {text: '177. 第N高的薪水', link: '/177'},
                {text: '178. 分数排名', link: '/178'},
                {text: '180. 连续出现的数字', link: '/180'},
                {text: '181. 超过经理收入的员工', link: '/181'},
                {text: '182. 查找重复的电子邮箱', link: '/182'},
                {text: '183. 从不订购的客户', link: '/183'},
                {text: '183. 从不订购的客户', link: '/183'},
                {text: '185. 部门工资前三高的所有员工', link: '/185'},
                {text: '196. 删除重复的电子邮箱', link: '/196'},
                {text: '197. 上升的温度', link: '/197'},
                {text: '262. 行程和用户', link: '/262'},
                {text: '511. 游戏玩法分析 I', link: '/511'},
                {text: '550. 游戏玩法分析 IV', link: '/550'},
                {text: '570. 至少有5名直接下属的经理', link: '/570'},
                {text: '577. 员工奖金', link: '/577'},
                {text: '584. 寻找用户推荐人', link: '/584'},
                {text: '585. 2016年的投资', link: '/585'},
                {text: '586. 订单最多的客户', link: '/586'},
                {text: '595. 大的国家', link: '/595'},
                {text: '596. 超过5名学生的课', link: '/596'},
                {text: '601. 体育馆的人流量', link: '/601'},
                {text: '602. 好友申请 II ：谁有最多的好友', link: '/602'},
                {text: '607. 销售员', link: '/607'},
                {text: '608. 树节点', link: '/608'},
                {text: '610. 判断三角形', link: '/610'},
                {text: '619. 只出现一次的最大数字', link: '/619'},
                {text: '620. 有趣的电影', link: '/620'},
                {text: '626. 换座位', link: '/626'},
                {text: '627. 变更性别', link: '/627'},
                {text: '1045. 买下所有产品的客户', link: '/1045'},
                {text: '1050. 合作过至少三次的演员和导演', link: '/1050'},
                {text: '1068. 产品销售分析 I', link: '/1068'}]
        }]
    }];
}