function bars() {
    return [{
        text: '第一页',
        base: '/lcof1/page1',
        collapsed: false,
        items: [
            {text: '剑指 Offer 03. 数组中重复的数字', link: '/03'},
            {text: '剑指 Offer 04. 二维数组中的查找', link: '/04'},
            {text: '剑指 Offer 05. 替换空格', link: '/05'},
            {text: '剑指 Offer 06. 从尾到头打印链表', link: '/06'},
            {text: '剑指 Offer 07. 重建二叉树', link: '/07'},
            {text: '剑指 Offer 09. 用两个栈实现队列', link: '/09'},
            {text: '剑指 Offer 10- I. 斐波那契数列', link: '/10I'},
            {text: '剑指 Offer 10- II. 青蛙跳台阶问题', link: '/10II'},
            {text: '剑指 Offer 11. 旋转数组的最小数字', link: '/11'},
            {text: '剑指 Offer 12. 矩阵中的路径', link: '/12'},
            {text: '剑指 Offer 13. 机器人的运动范围', link: '/13'},
            {text: '剑指 Offer 14- I. 剪绳子', link: '/14I'},
            {text: '剑指 Offer 14- II. 剪绳子 II', link: '/14II'},
            {text: '剑指 Offer 15. 二进制中1的个数', link: '/15'},
            {text: '剑指 Offer 16. 数值的整数次方', link: '/16'},
            {text: '剑指 Offer 17. 打印从1到最大的n位数', link: '/17'},
            {text: '剑指 Offer 18. 删除链表的节点', link: '/18'},
            {text: '剑指 Offer 19. 正则表达式匹配', link: '/19'},
            {text: '剑指 Offer 20. 表示数值的字符串', link: '/20'},
            {text: '剑指 Offer 21. 调整数组顺序使奇数位于偶数前面', link: '/21'},
            {text: '剑指 Offer 22. 链表中倒数第k个节点', link: '/22'},
            {text: '剑指 Offer 24. 反转链表', link: '/24'},
            {text: '剑指 Offer 25. 合并两个排序的链表', link: '/25'},
            {text: '剑指 Offer 26. 树的子结构', link: '/26'},
            {text: '剑指 Offer 27. 二叉树的镜像', link: '/27'},
            {text: '剑指 Offer 28. 对称的二叉树', link: '/28'},
            {text: '剑指 Offer 29. 顺时针打印矩阵', link: '/29'},
            {text: '剑指 Offer 30. 包含min函数的栈', link: '/30'},
            {text: '剑指 Offer 31. 栈的压入、弹出序列', link: '/31'},
            {text: '剑指 Offer 32 - I. 从上到下打印二叉树', link: '/32I'},
            {text: '剑指 Offer 32 - II. 从上到下打印二叉树 II', link: '/32II'},
            {text: '剑指 Offer 32 - III. 从上到下打印二叉树 III', link: '/32III'},
            {text: '剑指 Offer 33. 二叉搜索树的后序遍历序列', link: '/33'},
            {text: '剑指 Offer 34. 二叉树中和为某一值的路径', link: '/34'},
            {text: '剑指 Offer 35. 复杂链表的复制', link: '/35'},
            {text: '剑指 Offer 36. 二叉搜索树与双向链表', link: '/36'},
            {text: '剑指 Offer 37. 序列化二叉树', link: '/37'},
            {text: '剑指 Offer 38. 字符串的排列', link: '/38'},
            {text: '剑指 Offer 39. 数组中出现次数超过一半的数字', link: '/39'},
            {text: '剑指 Offer 40. 最小的k个数', link: '/40'},
            {text: '剑指 Offer 41. 数据流中的中位数', link: '/41'},
            {text: '剑指 Offer 42. 连续子数组的最大和', link: '/42'},
            {text: '剑指 Offer 43. 1～n 整数中 1 出现的次数', link: '/43'},
            {text: '剑指 Offer 44. 数字序列中某一位的数字', link: '/44'},
            {text: '剑指 Offer 45. 把数组排成最小的数', link: '/45'},
            {text: '剑指 Offer 46. 把数字翻译成字符串', link: '/46'},
            {text: '剑指 Offer 47. 礼物的最大价值', link: '/47'},
            {text: '剑指 Offer 48. 最长不含重复字符的子字符串', link: '/48'},
            {text: '剑指 Offer 49. 丑数', link: '/49'},
            {text: '剑指 Offer 50. 第一个只出现一次的字符', link: '/50'}
        ]
    }, {
        text: '第二页',
        base: '/lcof1/page2',
        collapsed: true,
        items: [
            {text: '剑指 Offer 51. 数组中的逆序对', link: '/51'},
            {text: '剑指 Offer 52. 两个链表的第一个公共节点', link: '/52'},
            {text: '剑指 Offer 53 - I. 在排序数组中查找数字 I', link: '/53I'},
            {text: '剑指 Offer 53 - II. 0～n-1中缺失的数字', link: '/53II'},
            {text: '剑指 Offer 54. 二叉搜索树的第k大节点', link: '/54'},
            {text: '剑指 Offer 55 - I. 二叉树的深度', link: '/55I'},
            {text: '剑指 Offer 55 - II. 平衡二叉树', link: '/55II'},
            {text: '剑指 Offer 56 - I. 数组中数字出现的次数', link: '/56I'},
            {text: '剑指 Offer 56 - II. 数组中数字出现的次数 II', link: '/56II'},
            {text: '剑指 Offer 57. 和为s的两个数字', link: '/57'},
            {text: '剑指 Offer 57 - II. 和为s的连续正数序列', link: '/57II'},
            {text: '剑指 Offer 58 - I. 翻转单词顺序', link: '/58I'},
            {text: '剑指 Offer 58 - II. 左旋转字符串', link: '/58II'},
            {text: '剑指 Offer 59 - I. 滑动窗口的最大值', link: '/59I'},
            {text: '剑指 Offer 59 - II. 队列的最大值', link: '/59II'},
            {text: '剑指 Offer 60. n个骰子的点数', link: '/60'},
            {text: '剑指 Offer 61. 扑克牌中的顺子', link: '/61'},
            {text: '剑指 Offer 62. 圆圈中最后剩下的数字', link: '/62'},
            {text: '剑指 Offer 63. 股票的最大利润', link: '/63'},
            {text: '剑指 Offer 64. 求1+2+…+n', link: '/64'},
            {text: '剑指 Offer 65. 不用加减乘除做加法', link: '/65'},
            {text: '剑指 Offer 66. 构建乘积数组', link: '/66'},
            {text: '剑指 Offer 67. 把字符串转换成整数', link: '/67'},
            {text: '剑指 Offer 68 - I. 二叉搜索树的最近公共祖先', link: '/68I'},
            {text: '剑指 Offer 68 - II. 二叉树的最近公共祖先', link: '/68II'}
        ]
    }];
}

function nav() {
    return {
        text: '剑指offer(第2版)',
        link: '/lcof1/index',
        activeMatch: '/lcof1/'
    };
}

export default {bars, nav}